#thread_learning: 
#	cc -Wall -pthread thread_learning.c -o thread_learning	

thread_learning_struct:
	cc -Wall -pthread thread_learning_struct.c -o thread_learning_struct

clean:
	rm -f thread_learning *.o
	rm -f thread_learning_struct *.o